### ISSUE TITLE
Previewing documentation is giving an error that it is not a valid JSON Schema

### ISSUE THREAD

**Issue by rwilkins108** [Apicurio/apicurio-studio#1366]
When previewing documentation for this API, getting the error:
```
Something went wrong...
"https://studio.apicur.io/download?type=api&format=json&dereference=true&id=24175" is not a valid JSON Schema
Stack trace
SyntaxError: "https://studio.apicur.io/download?type=api&format=json&dereference=true&id=24175" is not a valid JSON Schema
    at Function.syntax (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:28049)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:49:54299

ReDoc Version: 2.0.0-rc.48
Commit: 7b78e75
```
Can edit fine and editing shows 0 issues

Looks like this is a recurring issue as it's the same as #1036 and #1087

**Comment by EricWittmann** [comment]
Could you either download and attach the API design to this GH issue or (better) add me as a collaborator to the failing API?

Also, hitting that url ( https://studio.apicur.io/download?type=api&format=json&dereference=true&id=24175 ) in your browser might reveal some interesting result.

**Comment by rwilkins108** [comment]
@EricWittmann Thanks, we've added you as a collaborator.   
Going to that URL gives an HTTP 200 with the message "Internal Server Error".

Thanks for your help.

**Comment by EricWittmann** [comment]
No problem. I looked at it, but you have a few external `$ref`s in the document (I'm super happy to see that feature being used), so you will need to add me as a collaborator on any documents referenced by this one.  It looks like it's only #39013.

**Comment by EricWittmann** [comment]
But hey - at least you know I haven't given myself back-door/admin access to everyone's content. :)

**Comment by Stwissel** [comment]
@EricWittmann added you to 39013.
Question here: Can I make a project at least readOnly visible for anyone? 39013 is a Schema definition for jsCalendar which is a draft RFC which would be nice to show

**Comment by EricWittmann** [comment]
OK I can reproduce the issue and it has something to do with these references.  I will need to dig into this and figure out what's going on.  I'll report back here when I know more.

**Comment by EricWittmann** [comment]
Also regarding your question about Read Only - you can use the "Share Docs" feature to generate a read-only and public link to the documentation for an API:

![image](https://user-images.githubusercontent.com/1890703/103812729-f4c0ef00-502c-11eb-9b71-82df65dbb3fc.png)

However, ReDoc doesn't separately display the schemas, so that probably isn't very helpful to this use-case.  So I guess unfortunately no, there is no way to do what you ask right now.  Good feature request though if you want to open another issue. :)

**Comment by EricWittmann** [comment]
Fixed by https://github.com/Apicurio/apicurio-data-models/pull/223

This will be corrected in the next release.

**Comment by rwilkins108** [comment]
@EricWittmann  just checked, still having the same issue:
```
Something went wrong...
"https://studio.apicur.io/download?type=api&format=json&dereference=true&id=24175" is not a valid JSON Schema
Stack trace
SyntaxError: "https://studio.apicur.io/download?type=api&format=json&dereference=true&id=24175" is not a valid JSON Schema
    at Function.syntax (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:28051)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:49:54299

ReDoc Version: 2.0.0-rc.50
Commit: 8bee3d5
```

**Comment by EricWittmann** [comment]
Yes - you will get this error until we do another upstream release of Studio.  I'll try to get this done as soon as I can.

**Comment by Stwissel** [comment]
Bug still persists, including a "Server Error" when trying to download with "Dereference all external $refs"

**Comment by EricWittmann** [comment]
Try now.

**Comment by EricWittmann** [comment]
Wait - I'm getting a 503 now. :(  Worse than before.

**Comment by EricWittmann** [comment]
**Actually** try now - I believe the server has been updated to version 0.2.48.Final now.

**Comment by rwilkins108** [comment]
Yes, works for me.  Thanks!

**Comment by partialinfinity** [comment]
Updated to 2.48 and still receiving error when Preview Doc.
![image](https://user-images.githubusercontent.com/1331618/109314054-dd290a00-7816-11eb-99e2-0b7a6d319cdf.png)

Following the URL in browser displays only "Internal Server Error"

Our server is not public-facing, what is the best way to get you the information you need in order to debug the issue?

**Comment by EricWittmann** [comment]
@partialinfinity 
When you get the "Internal Server Error" on the server can you check the output logs from the application?  I would also suggest checking the browser console - there is a chance that some helpful debug information can be found there.
